test:
  adapter: mysql2
  encoding: UTF-8
  username: root
  password: purp1eb0y
  host: localhost
  database: testdb
  numprocesses: 8
  numfiles: 8
  datadir: /data/projectz/test/

production:
  adapter: mysql2
  encoding: UTF-8
  username: root
  password: purp1eb0y
  host: localhost
  database: productiondb
  numprocesses: 8
  numfiles: 8
  datadir: /data/projectz/test/

#  sitedata_dir: /data/projectz/test/trip
#  crawled_dir: /data/projectz/test/trip/crawl
#  hotels_dir: /data/projectz/test/trip/hotels
#  feed_dir: /data/projectz/test/trip/hotels/feeds

