
# On yelp, topsearches for san francisco is at http://http://www.yelp.com/topsearches

cities = [  
 "http://www.yelp.com/topsearches/",
 "http://www.yelp.com/topsearches/nyc",
 "http://www.yelp.com/topsearches/la",
 "http://www.yelp.com/topsearches/chicago",
]

cities1 = [
"http://www.yelp.com/topsearches/abilene-tx-us",
"http://www.yelp.com/topsearches/akron-oh-us",
"http://www.yelp.com/topsearches/albany-ny-us",
"http://www.yelp.com/topsearches/albuquerque",
"http://www.yelp.com/topsearches/allentown-pa",
"http://www.yelp.com/topsearches/amarillo-tx",
"http://www.yelp.com/topsearches/anchorage-ak",
"http://www.yelp.com/topsearches/ann-arbor-mi",
"http://www.yelp.com/topsearches/asheville-nc",
"http://www.yelp.com/topsearches/athens-ga",
"http://www.yelp.com/topsearches/atlanta",
"http://www.yelp.com/topsearches/augusta-ga",
"http://www.yelp.com/topsearches/austin",
"http://www.yelp.com/topsearches/bakersfield-ca",
"http://www.yelp.com/topsearches/baltimore",
"http://www.yelp.com/topsearches/barrie-on-ca",
"http://www.yelp.com/topsearches/baton-rouge-la",
"http://www.yelp.com/topsearches/beaumont-tx",
"http://www.yelp.com/topsearches/billings-mt",
"http://www.yelp.com/topsearches/birmingham-al",
"http://www.yelp.com/topsearches/bloomington-in",
"http://www.yelp.com/topsearches/boise-id",
"http://www.yelp.com/topsearches/boston",
"http://www.yelp.com/topsearches/buffalo",
"http://www.yelp.com/topsearches/cedar-rapids-ia",
"http://www.yelp.com/topsearches/charleston-sc",
"http://www.yelp.com/topsearches/charleston-wv",
"http://www.yelp.com/topsearches/charlotte-nc",
"http://www.yelp.com/topsearches/chattanooga-tn",
"http://www.yelp.com/topsearches/chicago",
"http://www.yelp.com/topsearches/cincinnati-oh",
"http://www.yelp.com/topsearches/cleveland",
"http://www.yelp.com/topsearches/colorado-springs-co",
"http://www.yelp.com/topsearches/columbia-sc",
"http://www.yelp.com/topsearches/columbia-mo",
"http://www.yelp.com/topsearches/columbus-oh",
"http://www.yelp.com/topsearches/columbus-ga",
"http://www.yelp.com/topsearches/corpus-christi-tx",
"http://www.yelp.com/topsearches/dallas",
"http://www.yelp.com/topsearches/dayton-oh",
"http://www.yelp.com/topsearches/daytona-beach-fl",
"http://www.yelp.com/topsearches/denver",
"http://www.yelp.com/topsearches/des-moines-ia",
"http://www.yelp.com/topsearches/detroit",
"http://www.yelp.com/topsearches/el-paso-tx",
"http://www.yelp.com/topsearches/erie-pa",
"http://www.yelp.com/topsearches/eugene-or",
"http://www.yelp.com/topsearches/evansville-in",
"http://www.yelp.com/topsearches/fairfield-ct",
"http://www.yelp.com/topsearches/fort-lauderdale-fl",
"http://www.yelp.com/topsearches/fort-myers-fl-us",
"http://www.yelp.com/topsearches/fort-wayne-in",
"http://www.yelp.com/topsearches/fort-worth",
"http://www.yelp.com/topsearches/appleton-wi",
"http://www.yelp.com/topsearches/fresno-ca",
"http://www.yelp.com/topsearches/gainesville-fl",
"http://www.yelp.com/topsearches/grand-rapids-mi",
"http://www.yelp.com/topsearches/green-bay-wi",
"http://www.yelp.com/topsearches/greenville-sc",
"http://www.yelp.com/topsearches/virginia-beach-va-us",
"http://www.yelp.com/topsearches/harrisburg-pa",
"http://www.yelp.com/topsearches/hartford",
"http://www.yelp.com/topsearches/honolulu",
"http://www.yelp.com/topsearches/houston",
"http://www.yelp.com/topsearches/huntsville-al",
"http://www.yelp.com/topsearches/indianapolis-in",
"http://www.yelp.com/topsearches/ontario-ca",
"http://www.yelp.com/topsearches/jackson-ms",
"http://www.yelp.com/topsearches/jax",
"http://www.yelp.com/topsearches/kalamazoo-mi",
"http://www.yelp.com/topsearches/kansas-city-mo",
"http://www.yelp.com/topsearches/kelowna-bc-ca",
"http://www.yelp.com/topsearches/kingston-on-ca",
"http://www.yelp.com/topsearches/waterloo-on-ca",
"http://www.yelp.com/topsearches/knoxville-tn",
"http://www.yelp.com/topsearches/lakeland-fl",
"http://www.yelp.com/topsearches/east-lansing-mi",
"http://www.yelp.com/topsearches/las-vegas",
"http://www.yelp.com/topsearches/lexington-ky",
"http://www.yelp.com/topsearches/lincoln-ne",
"http://www.yelp.com/topsearches/little-rock-ar",
"http://www.yelp.com/topsearches/london-on-ca",
"http://www.yelp.com/topsearches/la",
"http://www.yelp.com/topsearches/san-gabriel-ca",
"http://www.yelp.com/topsearches/san-fernando-valley-ca",
"http://www.yelp.com/topsearches/louisville",
"http://www.yelp.com/topsearches/lubbock-tx",
"http://www.yelp.com/topsearches/macon-ga",
"http://www.yelp.com/topsearches/madison",
"http://www.yelp.com/topsearches/memphis",
"http://www.yelp.com/topsearches/miami",
"http://www.yelp.com/topsearches/midland-tx",
"http://www.yelp.com/topsearches/milwaukee",
"http://www.yelp.com/topsearches/minneapolis",
"http://www.yelp.com/topsearches/mobile-al-us",
"http://www.yelp.com/topsearches/modesto-ca-us",
"http://www.yelp.com/topsearches/montgomery-al",
"http://www.yelp.com/topsearches/sonoma-ca-us",
"http://www.yelp.com/topsearches/naples-fl",
"http://www.yelp.com/topsearches/nashville",
"http://www.yelp.com/topsearches/new-orleans",
"http://www.yelp.com/topsearches/nyc",
"http://www.yelp.com/topsearches/ocala-fl-us",
"http://www.yelp.com/topsearches/ogden-ut-us",
"http://www.yelp.com/topsearches/oklahoma-city",
"http://www.yelp.com/topsearches/omaha-ne-us",
"http://www.yelp.com/topsearches/oc",
"http://www.yelp.com/topsearches/orlando-fl",
"http://www.yelp.com/topsearches/palm-beach-fl",
"http://www.yelp.com/topsearches/pensacola-fl-us",
"http://www.yelp.com/topsearches/philadelphia",
"http://www.yelp.com/topsearches/phoenix",
"http://www.yelp.com/topsearches/pittsburgh",
"http://www.yelp.com/topsearches/portland",
"http://www.yelp.com/topsearches/portland-me",
"http://www.yelp.com/topsearches/providence",
"http://www.yelp.com/topsearches/raleigh-nc",
"http://www.yelp.com/topsearches/regina-sk-ca",
"http://www.yelp.com/topsearches/reno-nv-us",
"http://www.yelp.com/topsearches/richmond",
"http://www.yelp.com/topsearches/roanoke-va",
"http://www.yelp.com/topsearches/rochester-ny-us",
"http://www.yelp.com/topsearches/rockford-il",
"http://www.yelp.com/topsearches/sacramento",
"http://www.yelp.com/topsearches/salem-or-us",
"http://www.yelp.com/topsearches/salt-lake-city",
"http://www.yelp.com/topsearches/san-angelo-tx",
"http://www.yelp.com/topsearches/san-antonio-tx",
"http://www.yelp.com/topsearches/san-diego",
"http://www.yelp.com/topsearches",
"http://www.yelp.com/topsearches/san-jose",
"http://www.yelp.com/topsearches/santa-barbara-ca",
"http://www.yelp.com/topsearches/santa-clarita-ca",
"http://www.yelp.com/topsearches/santa-cruz-ca-us",
"http://www.yelp.com/topsearches/savannah-ga",
"http://www.yelp.com/topsearches/tacoma-wa-us",
"http://www.yelp.com/topsearches/seattle",
"http://www.yelp.com/topsearches/shreveport-la",
"http://www.yelp.com/topsearches/sioux-falls-sd",
"http://www.yelp.com/topsearches/south-bend-in-us",
"http://www.yelp.com/topsearches/spokane-wa",
"http://www.yelp.com/topsearches/springfield-mo",
"http://www.yelp.com/topsearches/springfield-ma",
"http://www.yelp.com/topsearches/st-catharines-on-ca",
"http://www.yelp.com/topsearches/st-john-s-nl-ca",
"http://www.yelp.com/topsearches/st-louis",
"http://www.yelp.com/topsearches/stockton-ca",
"http://www.yelp.com/topsearches/sudbury-ma",
"http://www.yelp.com/topsearches/syracuse-ny-us",
"http://www.yelp.com/topsearches/tallahassee-fl-us",
"http://www.yelp.com/topsearches/tampa-bay-fl",
"http://www.yelp.com/topsearches/toledo-oh-us",
"http://www.yelp.com/topsearches/topeka-ks",
"http://www.yelp.com/topsearches/tucson-az",
"http://www.yelp.com/topsearches/tulsa-ok",
"http://www.yelp.com/topsearches/vancouver-wa",
"http://www.yelp.com/topsearches/ventura-county-ca",
"http://www.yelp.com/topsearches/westchester-county-ny-us",
"http://www.yelp.com/topsearches/wichita-ks",
"http://www.yelp.com/topsearches/wilmington-de",
"http://www.yelp.com/topsearches/worcester-ma",
"http://www.yelp.com/topsearches/youngstown-oh"
]

cities.each do |i| 
  #url = "http://http://www.yelp.com/topsearches/" + i
  url = i

  parts = url.split('/')
  if parts[4].nil? || parts[4].empty?
    out = "yelp_keywords/" + "san-francisco" 
  else
    out = "yelp_keywords/" + parts[4]
  end
  program = "ruby -rubygems crawl_test.rb -u #{url} -p \"//div[@class[contains(.,'column')]]/a\" -q \"/html/body/div[2]/div[3]/div[2]/div[3]/a/@href\" -o #{out}"
  puts program
  system(program)
end


