require 'pp'

files_cities1 = {
"san-francisco" => "San Francisco",
"la" => "Los Angeles"
}

files1 = [
"san-francisco", 
"la" 
]

city_words1 = [
"San Francisco", 
"Los Angeles" 
]

files_cities = {
"san-francisco" => "San Francisco",
"la" => "Los Angeles",
"nyc" => "New York",
"chicago" => "Chicago",
"san-diego" => "San Diego",
"san-jose" => "San Jose",
"seattle" => "Seattle",
"boston" => "Boston",
"austin" => "Austin",
"las-vegas" => "Las Vegas",
"philadelphia" => "Philadelphia",
"portland" => "Portland",
"houston" => "Houston",
"sacramento" => "Sacramento",
"honolulu" => "Honolulu",
"atlanta" => "Atlanta",
"oc" => "Orange County",
"denver" => "Denver",
"dallas" => "Dallas",
"phoenix" => "Phoenix",
"miami" => "Miami",
"minneapolis" => "Minneapolis",
"new-orleans" => "New Orleans",
"st-louis" => "Saint Louis",
"baltimore" => "Baltimore",
"san-antonio-tx" => "San Antonio",
"orlando-fl" => "Orlando",
"santa-barbara-ca" => "Santa Barbara",
"santa-cruz-ca-us" => "Santa Cruz",
"san-gabriel-ca" => "San Gabriel",
"pittsburgh" => "Pittsburgh",
"fort-lauderdale-fl" => "Fort Lauderdale",
"detroit" => "Detroit",
"charlotte-nc" => "Charlotte",
"nashville" => "Nashville",
"columbus-oh" => "Columbus",
"salt-lake-city" => "Salt Lake City",
"providence" => "Providence",
"milwaukee" => "Milwaukee",
"kansas-city-mo" => "Kansas City",
"indianapolis-in" => "Indianapolis",
"cincinnati-oh" => "Cincinnati",
"tucson-az" => "Tucson",
"ann-arbor-mi" => "Ann Arbor",
"fort-worth" => "Fort Worth",
"raleigh-nc" => "Raleigh",
"virginia-beach-va-us" => "Virginia Beach",
"richmond" => "Richmond",
"cleveland" => "Cleveland",
"colorado-springs-co" => "Colorado Springs",
"albuquerque" => "Albuquerque",
"madison" => "Madison",
"santa-clarita-ca" => "Santa Clarita",
"reno-nv-us" => "Reno",
"san-fernando-valley-ca" => "San Fernando Valley",
"fresno-ca" => "Fresno",
"tacoma-wa-us" => "Tacoma",
"jax" => "Jacksonville",
"ontario-ca" => "Ontario",
"stockton-ca" => "Stockton",
"oklahoma-city" => "Oklahoma City",
"bakersfield-ca" => "Bakersfield",
"louisville" => "Louisville",
"charleston-sc" => "Charleston",
"vancouver-wa" => "Vancouver",
"eugene-or" => "Eugene",
"portland-me" => "Portland",
"buffalo" => "Buffalo",
"sonoma-ca-us" => "Sonoma",
"modesto-ca-us" => "Modesto",
"memphis" => "Memphis",
"grand-rapids-mi" => "Grand Rapids",
"omaha-ne-us" => "Omaha",
"worcester-ma" => "Worcester",
"rochester-ny-us" => "Rochester",
"gainesville-fl" => "Gainesville",
"savannah-ga" => "Savannah",
"albany-ny-us" => "Albany",
"birmingham-al" => "Birmingham",
"asheville-nc" => "Asheville",
"hartford" => "Hardford",
"wilmington-de" => "Wilmington",
"spokane-wa" => "Spokane",
"westchester-county-ny-us" => "Westchester County",
"anchorage-ak" => "Anchorage",
"boise-id" => "Boise",
"baton-rouge-la" => "Baton Rouge",
"el-paso-tx" => "El Paso",
"des-moines-ia" => "Des Moines",
"syracuse-ny-us" => "Syracuse",
"bloomington-in" => "Bloomington",
"columbia-sc" => "Columbia",
"little-rock-ar" => "Little Rock",
"lexington-ky" => "Lexington",
"naples-fl" => "Naples",
"tallahassee-fl-us" => "Tallahassee",
"knoxville-tn" => "Knoxville",
"harrisburg-pa" => "Harrisburg",
"salem-or-us" => "Salem",
"greenville-sc" => "Greenville",
"fort-myers-fl-us" => "Fort Myers",
"dayton-oh" => "Dayton",
"lincoln-ne" => "Lincoln",
"corpus-christi-tx" => "Corpus Christi",
"chattanooga-tn" => "Chattanooga",
"tulsa-ok" => "Tulsa",
"wichita-ks" => "Wichita",
"springfield-mo" => "Springfield",
"pensacola-fl-us" => "Pensacola",
"south-bend-in-us" => "Sound Bend",
"allentown-pa" => "Allentown",
"huntsville-al" => "Huntsville",
"london-on-ca" => "London",
"athens-ga" => "Athens",
"daytona-beach-fl" => "Daytona Beach",
"springfield-ma" => "Springfield",
"east-lansing-mi" => "East Lansing",
"kalamazoo-mi" => "Kalamazoo",
"fairfield-ct" => "Fairfield",
"cedar-rapids-ia" => "Cedar Rapids",
"toledo-oh-us" => "Toledo",
"rockford-il" => "Rockford",
"fort-wayne-in" => "Fort Wayne",
"lubbock-tx" => "Lubbock",
"columbia-mo" => "Columbia",
"akron-oh-us" => "Akron",
"augusta-ga" => "Augusta",
"columbus-ga" => "Columbus",
"green-bay-wi" => "Green Bay",
"montgomery-al" => "Montgomery",
"roanoke-va" => "Roanoke",
"sioux-falls-sd" => "Sious Falls",
"ventura-county-ca" => "Venture County",
"appleton-wi" => "Appleton",
"shreveport-la" => "Shreveport",
"palm-beach-fl" => "Palm Beach",
"mobile-al-us" => "Mobile",
"charleston-wv" => "Charleston",
"amarillo-tx" => "Amarillo",
"jackson-ms" => "Jackson",
"billings-mt" => "Billings",
"lakeland-fl" => "Lakeland",
"evansville-in" => "Evansville",
"san-angelo-tx" => "San Angelo",
"ogden-ut-us" => "Ogden",
"sudbury-ma" => "Sudbury",
"beaumont-tx" => "Beaumont",
"abilene-tx-us" => "Abilene",
"ocala-fl-us" => "Ocala",
"macon-ga" => "Macon",
"erie-pa" => "Erie",
"midland-tx" => "Midland",
"topeka-ks" => "Topeka",
"youngstown-oh" => "Youngstown",
"tampa-bay-fl" => "Tampa Bay"
}

files = [
"san-francisco",
"la",
"nyc",
"chicago",
"san-diego",
"san-jose",
"seattle",
"boston",
"austin",
"las-vegas",
"philadelphia",
"portland",
"houston",
"sacramento",
"honolulu",
"atlanta",
"oc",
"denver",
"dallas",
"phoenix",
"miami",
"minneapolis",
"new-orleans",
"st-louis",
"baltimore",
"san-antonio-tx",
"orlando-fl",
"santa-barbara-ca",
"santa-cruz-ca-us",
"san-gabriel-ca",
"pittsburgh",
"fort-lauderdale-fl",
"detroit",
"charlotte-nc",
"nashville",
"columbus-oh",
"salt-lake-city",
"providence",
"milwaukee",
"kansas-city-mo",
"indianapolis-in",
"cincinnati-oh",
"tucson-az",
"ann-arbor-mi",
"fort-worth",
"raleigh-nc",
"virginia-beach-va-us",
"richmond",
"cleveland",
"colorado-springs-co",
"albuquerque",
"madison",
"santa-clarita-ca",
"reno-nv-us",
"san-fernando-valley-ca",
"fresno-ca",
"tacoma-wa-us",
"jax",
"ontario-ca",
"stockton-ca",
"oklahoma-city",
"bakersfield-ca",
"louisville",
"charleston-sc",
"vancouver-wa",
"eugene-or",
"portland-me",
"buffalo",
"sonoma-ca-us",
"modesto-ca-us",
"memphis",
"grand-rapids-mi",
"omaha-ne-us",
"worcester-ma",
"rochester-ny-us",
"gainesville-fl",
"savannah-ga",
"albany-ny-us",
"birmingham-al",
"asheville-nc",
"hartford",
"wilmington-de",
"spokane-wa",
"westchester-county-ny-us",
"anchorage-ak",
"boise-id",
"baton-rouge-la",
"el-paso-tx",
"des-moines-ia",
"syracuse-ny-us",
"bloomington-in",
"columbia-sc",
"little-rock-ar",
"lexington-ky",
"naples-fl",
"tallahassee-fl-us",
"knoxville-tn",
"harrisburg-pa",
"salem-or-us",
"greenville-sc",
"fort-myers-fl-us",
"dayton-oh",
"lincoln-ne",
"corpus-christi-tx",
"chattanooga-tn",
"tulsa-ok",
"wichita-ks",
"springfield-mo",
"pensacola-fl-us",
"south-bend-in-us",
"allentown-pa",
"huntsville-al",
"london-on-ca",
"athens-ga",
"daytona-beach-fl",
"springfield-ma",
"east-lansing-mi",
"kalamazoo-mi",
"fairfield-ct",
"cedar-rapids-ia",
"toledo-oh-us",
"rockford-il",
"fort-wayne-in",
"lubbock-tx",
"columbia-mo",
"akron-oh-us",
"augusta-ga",
"columbus-ga",
"green-bay-wi",
"montgomery-al",
"roanoke-va",
"sioux-falls-sd",
"ventura-county-ca",
"appleton-wi",
"shreveport-la",
"palm-beach-fl",
"mobile-al-us",
"charleston-wv",
"amarillo-tx",
"jackson-ms",
"billings-mt",
"lakeland-fl",
"evansville-in",
"san-angelo-tx",
"ogden-ut-us",
"sudbury-ma",
"beaumont-tx",
"abilene-tx-us",
"ocala-fl-us",
"macon-ga",
"erie-pa",
"midland-tx",
"topeka-ks",
"youngstown-oh",
"tampa-bay-fl"
]

city_names = [
 "San Francisco",
 "Los Angeles",
 "New York",
 "Chicago",
 "San Diego",
 "San Jose",
 "Seattle",
 "Boston",
 "Austin",
 "Las Vegas",
 "Philadelphia",
 "Portland",
 "Houston",
 "Sacramento",
 "Honolulu",
 "Atlanta",
 "Orange County",
 "Denver",
 "Dallas",
 "Phoenix",
 "Miami",
 "Minneapolis",
 "New Orleans",
 "Saint Louis",
 "Baltimore",
 "San Antonio",
 "Orlando",
 "Santa Barbara",
 "Santa Cruz",
 "San Gabriel",
 "Pittsburgh",
 "Fort Lauderdale",
 "Detroit",
 "Charlotte",
 "Nashville",
 "Columbus",
 "Salt Lake City",
 "Providence",
 "Milwaukee",
 "Kansas City",
 "Indianapolis",
 "Cincinnati",
 "Tucson",
 "Ann Arbor",
 "Fort Worth",
 "Raleigh",
 "Virginia Beach",
 "Richmond",
 "Cleveland",
 "Colorado Springs",
 "Albuquerque",
 "Madison",
 "Santa Clarita",
 "Reno",
 "San Fernando Valley",
 "Fresno",
 "Tacoma",
 "Jacksonville",
 "Ontario",
 "Stockton",
 "Oklahoma City",
 "Bakersfield",
 "Louisville",
 "Charleston",
 "Vancouver",
 "Eugene",
 "Portland",
 "Buffalo",
 "Sonoma",
 "Modesto",
 "Memphis",
 "Grand Rapids",
 "Omaha",
 "Worcester",
 "Rochester",
 "Gainesville",
 "Savannah",
 "Albany",
 "Birmingham",
 "Asheville",
 "Hardford",
 "Wilmington",
 "Spokane",
 "Westchester County",
 "Anchorage",
 "Boise",
 "Baton Rouge",
 "El Paso",
 "Des Moines",
 "Syracuse",
 "Bloomington",
 "Columbia",
 "Little Rock",
 "Lexington",
 "Naples",
 "Tallahassee",
 "Knoxville",
 "Harrisburg",
 "Salem",
 "Greenville",
 "Fort Myers",
 "Dayton",
 "Lincoln",
 "Corpus Christi",
 "Chattanooga",
 "Tulsa",
 "Wichita",
 "Springfield",
 "Pensacola",
 "Sound Bend",
 "Allentown",
 "Huntsville",
 "London",
 "Athens",
 "Daytona Beach",
 "Springfield",
 "East Lansing",
 "Kalamazoo",
 "Fairfield",
 "Cedar Rapids",
 "Toledo",
 "Rockford",
 "Fort Wayne",
 "Lubbock",
 "Columbia",
 "Akron",
 "Augusta",
 "Columbus",
 "Green Bay",
 "Montgomery",
 "Roanoke",
 "Sious Falls",
 "Venture County",
 "Appleton",
 "Shreveport",
 "Palm Beach",
 "Mobile",
 "Charleston",
 "Amarillo",
 "Jackson",
 "Billings",
 "Lakeland",
 "Evansville",
 "San Angelo",
 "Ogden",
 "Sudbury",
 "Beaumont",
 "Abilene",
 "Ocala",
 "Macon",
 "Erie",
 "Midland",
 "Topeka",
 "Youngstown",
 "Tampa Bay"
]

word_freq = {}
files_cities.each do |f, t|
  cnt = 1
  File.open(f,"r").each do |line|
    line.strip!
    w = line.split(/#{t}/)[0].strip
    word_freq[w] = {} if word_freq[w].nil?
    word_freq[w][f] = cnt
    cnt += 1
    break if cnt > 100
  end
end

#pp word_freq

# keyword popularity
kword_popularity = {}
word_freq.each do |k, v|
    kword_popularity[k] = v.size
end
kword_popularity = kword_popularity.sort_by { |k, v| -v }

kword_avg_ranking = {}
word_freq.each do |k, v|
    sum = 0
    v.each do |i| 
      sum += i[1]
    end
    avg = sum.to_f / v.size
    kword_avg_ranking[k] = avg
end
kword_avg_ranking = kword_avg_ranking.sort_by { |k, v| v }

# print in tsv format
# print header
files_header = ""
files.each do |c|
    files_header += "	" + c
end

city_name_header = ""
city_names.each do |c|
    city_name_header += "	" + c
end


puts "Yelp URL Slug		#{files_header}"
puts "Search Terms	Popularity	Average Ranking#{city_name_header}"
kword_popularity.each do |w,v|
    avg_rank  = ""
    kword_avg_ranking.each{|ak,av| avg_rank = av if ak == w} 
    str = "#{w}	#{v}	#{avg_rank}"
    files.each do |c|
        if word_freq[w][c].nil?
            str = str + "	" 
        else
            str = str + "	" + word_freq[w][c].to_s 
        end
    end
    puts str
end



