

production:
    hotels_list:  /data/crawl/ta/hotels
    dest_html_location:  /data/crawl/ta/data_ta
    hotels_reviews_html_location:  /data/crawl/ta/data_ta_hotel_and_reviews
    reviews_feed:  /data/crawl/ta/reviews_feed
    hotels_list_split_size:  11000

    city_urls_file: 

